
[tool.pycrate]
name = "my_project"
version = "0.1.0"
description = "A new Python project"

[tool.pycrate.dependencies]
pydantic = "latest"

[tool.pycrate.dev-dependencies]
pytest = "latest"

[tool.pycrate.test-dependencies]

[tool.pycrate.scripts]
main = "src/main.py"

[tool.pycrate.python]
version = ">=3.6"
